apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis
  namespace: redis-sentinel
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: redis-sentinel
---
