apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-proxy
  namespace: redis-sentinel
  labels:
    app.kubernetes.io/name: redis-sentinel-proxy
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: redis
    name: redis
  selector:
    app.kubernetes.io/name: redis-sentinel-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel-proxy
  namespace: redis-sentinel
  labels:
    app.kubernetes.io/name: redis-sentinel-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-sentinel-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-sentinel-proxy
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: redis-sentinel-proxy
                topologyKey: kubernetes.io/hostname
              weight: 1
      containers:
      - image: flant/redis-sentinel-proxy:v2.0.2
        name: sentinel-proxy
        command:
        - /usr/local/bin/redis-sentinel-proxy
        - -master
        - mymaster
        - -listen
        - ":6379"
        - -sentinel
        - "redis.redis-sentinel.svc.cluster.local:26379"
        - -resolve-retries
        - "5"
        ports:
        - containerPort: 6379
          name: redis
        resources:
          limits:
            memory: 15Mi
          requests:
            memory: 7Mi
            cpu: 5m
