apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-proxy
  namespace: redis-sentinel
  labels:
    app.kubernetes.io/name: redis-sentinel-proxy
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: redis
    name: redis
  selector:
    app.kubernetes.io/name: redis-sentinel-proxy
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-sentinel-proxy
  namespace: redis-sentinel
  labels:
    app.kubernetes.io/name: redis-sentinel-proxy
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-sentinel-proxy
    spec:
      containers:
      - image: flant/redis-sentinel-proxy:v2.0.2
        name: sentinel-proxy
        command:
        - /usr/local/bin/redis-sentinel-proxy
        - -master
        - mymaster
        - -listen
        - "6379"
        - -sentinel
        - redis-headless.redis-sentinel.svc.cluster.local
        ports:
        - containerPort: 6379
          name: redis
