apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: redis
spec:
  encryptedData:
    redis-password: AgBX0Av55kOkDUwQniK7qkmaMqe9LyRbo+vaiMdgqA82BaC/OfSmX7zILbMJ2Nx0EMUoAPpecfR22xxLU6Q2gmYde7fUsAor7mv+Ww/Vzl3doZZcdnYPGTXa7hxaYl1JY3zJnaQ4pwSgHICMm3I4uGJpMSVCaKyqN+bnIDJ01GnSPENCvj/DroNG9bwe+KQI53BKU0d2U8NHesdEamUwZsaO+YHg0IOi6IkqLYS5UXE/MVUW/aI+fYgcr1U/9RbW2nNMOFSuUqk8cct7SS7LkSxcTe84EkAvOB+DEH7oATsvaWcWbRD+njXFWU4MNEvF/ULg6KXdYhxZ5A5JyRKcPX2vx58o1HmMqkr4i7eZMUVbi8Dkm2ZmG3nKpCwwbKn2i7+GOvoOlalUzhi5T9bhk5I/CZkSf+TvPuMCl0CD7pGd4/3qdO05CRWPAlFglA09FqrlsyTwlkeHKioaYoLTkPC0rlVToqVdT1Tcp81Tw65PPf3kNvN27Es47uL+7oM9g6QL+PBd+Cw4O4IKISBT8lrzsy8/GOipIRTXx26FoMeXbq1QKy4RmwYpivYgkmoVdZi6BcEBae9LMh//SbwgiHujDSIVbaI88Q4AzziocvpqWxKQhKPmoZ2jbga9drVwYuRY4wvCPtzDxJzs6Ab5mDa8LhWdL4vjo1sY2Squ9o8JCMc+40raMxCQxwldtBqefUeJSMk/Sm/kdxsE93ZvcbY00TlLkQ==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: redis
        app.kubernetes.io/name: redis
      name: redis
      namespace: redis
    type: Opaque

