apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: redis-sentinel
spec:
  encryptedData:
    redis-password: AgB4VLrZSYZYBybFL1YK4m7v3+lEsKzF/46Zlu5dx36gAFnFsa+fYcb2sfbx3ULB8Y6zC0C5UR7ZhWxKpC9gcJ1Jtn0z4foDUPRfsWQR5gU4OQDJKIvU5ZvnO0LFMx653W+igdnAivCCDZFdhkqQnh/MJanRJ/FG3vszbiTj0v5MRKpcnXxLSma7u1+mtfZA41TpPBcxGxZ6tZP0JU0T8Oe1cyfxVx+eCJQCjWRM8/JeUuRQOgJXG+k7uwadSlKckQlbvpRfUBlJl+DVUfd+oPSd1brQWTfgJm0f8nu1NFcchHS1VyPHNQHG8hQzrDQuiU036m5TiYfY617hnyK4VPM1fL3GwPz89qQaO9cK1vwNSnewjQT3jKvQlDQjTcrTqz07zeY0ChcNQ2NTX6gPCV7JNAGhVU5Yxt0qfxQSnLUJJ4MU1qt7MZut2C0gLGR9jDQwPNG602WYCwWItpvO4de0sRTgjrj8834l5mmbgbpDyR0OQaqeuY4MmyUW/uJGPHinLtNcMZm3X5mAgqgKnEM0hNd7d41jFdXZye7sZ+xrOcQTJpy13Et89whlAwWe0YZPYtd9VHze/vvnhg80eiJ1rYd9RN1Kff2hgFoqVlYigE9cD4DcqtAz6xlPX6iuXnjBtlSxAPj5uLOcUKzK2bOhBcRd/q1F3d6BW4K5vqLQcRldOo3vs0U28R7uS/JHEkttFwVyS88sqo92VnAjwavPIj7VzA==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/instance: redis-sentinel
      name: redis
      namespace: redis
    type: Opaque

