apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: redis
  namespace: redis-sentinel
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:  StatefulSet
    name: redis-node
  updatePolicy:
    updateMode: "Off"
---
