apiVersion: batch/v1
kind: CronJob
metadata:
  name: bucket-sync
  namespace: default
  labels:
    app.kubernetes.io/name: bucket-sync
  annotations:
    description: |
      Syncs media from old object storage to new object storage
spec:
  schedule: 0 0 * * 0
  concurrencyPolicy: Forbid
  suspend: true
  jobTemplate:
    spec:
      backoffLimit: 3
      parallelism: 1
      template:
        metadata:
          name: bucket-sync
        spec:
          restartPolicy: OnFailure
          containers:
            - name: bucket-sync
              image: "rclone/rclone:1"
              imagePullPolicy: IfNotPresent
              command:
                - sh
                - -c
                - |
                  rclone listremotes --long
                  rclone sync --progress scaleway:k8s.social civo:k8s.social-media
              volumeMounts:
                - name: config
                  mountPath: /config/rclone
          volumes:
            - name: config
              secret:
                secretName: bucket-sync-config

---
