
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8085"
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
        - image: registry.k8s.io/autoscaling/cluster-autoscaler:v1.29.1
          name: cluster-autoscaler
          imagePullPolicy: Always
          resources:
            limits:
              memory: 300Mi
            requests:
              cpu: 50m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=civo
            - --nodes=2:5:workers
            - --skip-nodes-with-local-storage=false
            - --skip-nodes-with-system-pods=false
            - --scale-down-delay-after-add=20m
            - --scale-down-unneeded-time=10m
            - --scale-down-unready-time=10m
            - --scan-interval=1m
            - --max-node-provision-time=10m
            - --cordon-node-before-terminating=true
          env:
            - name: CIVO_API_URL
              valueFrom:
                secretKeyRef:
                  key: api-url
                  name: cluster-autoscaler
            - name: CIVO_API_KEY
              valueFrom:
                secretKeyRef:
                  key: api-key
                  name: cluster-autoscaler
            - name: CIVO_CLUSTER_ID
              valueFrom:
                secretKeyRef:
                  key: cluster-id
                  name: cluster-autoscaler
            - name: CIVO_REGION
              valueFrom:
                secretKeyRef:
                  key: region
                  name: cluster-autoscaler
