apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: seasled-secrets-controller
  namespace: kube-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:  Deployment
    name: seasled-secrets-controller
  updatePolicy:
    updateMode: "Off"
---
