apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:  Deployment
    name: kube-state-metrics
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prometheus-prometheus
  namespace: monitoring
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:  StatefulSet
    name: prometheus-prometheus
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: loki
  namespace: monitoring
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:  StatefulSet
    name: loki
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: promtail
  namespace: monitoring
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:  DaemonSet
    name: promtail
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prometheus-node-exporter
  namespace: monitoring
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:  DaemonSet
    name: prometheus-node-exporter
  updatePolicy:
    updateMode: "Off"
---
