apiVersion: v1
kind: ConfigMap
metadata:
  name: mastodon-env
  namespace: mastodon
  labels:
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/instance: mastodon
data:
  DEFAULT_LOCALE: en
  LOCAL_DOMAIN: k8s.social
  MALLOC_ARENA_MAX: "2"
  NODE_ENV: "production"
  RAILS_ENV: "production"
  STREAMING_CLUSTER_NUM: "0"
  WEB_CONCURRENCY: "0"
  UPDATE_CHECK_URL: ""
---
