apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-replicas
  namespace: redis
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/component: replica
      app.kubernetes.io/name: redis
---
