apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: redis
spec:
  encryptedData:
    redis-password: AgB4VLrZSYZYBybFL1YK4m7v3+lEsKzF/46Zlu5dx36gAFnFsa+fYcb2sfbx3ULB8Y6zC0C5UR7ZhWxKpC9gcJ1Jtn0z4foDUPRfsWQR5gU4OQDJKIvU5ZvnO0LFMx653W+igdnAivCCDZFdhkqQnh/MJanRJ/FG3vszbiTj0v5MRKpcnXxLSma7u1+mtfZA41TpPBcxGxZ6tZP0JU0T8Oe1cyfxVx+eCJQCjWRM8/JeUuRQOgJXG+k7uwadSlKckQlbvpRfUBlJl+DVUfd+oPSd1brQWTfgJm0f8nu1NFcchHS1VyPHNQHG8hQzrDQuiU036m5TiYfY617hnyK4VPM1fL3GwPz89qQaO9cK1vwNSnewjQT3jKvQlDQjTcrTqz07zeY0ChcNQ2NTX6gPCV7JNAGhVU5Yxt0qfxQSnLUJJ4MU1qt7MZut2C0gLGR9jDQwPNG602WYCwWItpvO4de0sRTgjrj8834l5mmbgbpDyR0OQaqeuY4MmyUW/uJGPHinLtNcMZm3X5mAgqgKnEM0hNd7d41jFdXZye7sZ+xrOcQTJpy13Et89whlAwWe0YZPYtd9VHze/vvnhg80eiJ1rYd9RN1Kff2hgFoqVlYigE9cD4DcqtAz6xlPX6iuXnjBtlSxAPj5uLOcUKzK2bOhBcRd/q1F3d6BW4K5vqLQcRldOo3vs0U28R7uS/JHEkttFwVyS88sqo92VnAjwavPIj7VzA==
    secretText: AgCrgagbPZZx94WBZKx7q6zY3gF7SMO9XgOT2YDP2Zau4nUwrQ5zfOAX3uHJv8imwdW+PyDYpTW9VhW7LFsm/S3bUp+0Wo5pss8FkriTGNRVNO8C0ezQVfV3kL5gtSlrTwz7Kps+MjG/j2uZHDXW19meVkqRMgZPQIiaBEC1uXEhVNhyNXBaOIT6W+V3hE1JDMWMXTkuB0tdgmWAkVCKumqTBYSSVwwI65MkPW3LWoUJGxXnwxgNEn9n9jNmiKmOqwOhazPp7XKoOjUJV8AXy5d9gg63q+1UErjfV+X4byZc2LKAxoVnEhqCY679/IsxhbKLtnNXBRchuKlWVJnKjFNhCPRzQSLILj6wSoB7FT7XujksMwBD4Tm2TfMrbuS1UzKv3nioJhpqxRC9aqFk66w19LkrUd9EBpYWMtKejaw48s4xiaHqIgEgvWdaApPC7g4r6xYOZsOetzrmATCCWGVhACA9LdaByzl0R9Htze2AWHnR7MMlJu/LuRXIsAjI9iZ6eMLcISc8lCcby7uHbqVXZlpal6Y6FhbVAJ4HKWJpFRq5LJ+IEarePfnAJwnHZePwNDPaZBi4g5QFTVGKjpeNfwUgpo56DuoB731zvj9+M+Jc+Dg9CnjXnobyCmn0++2SI7AAb5durh79qAtNNmCRgHEWztPV9e7NEMee309g0Lr95OUbw+TYqStkOaukKQuj6Be6kfAMVoK0E3Y3OpqQqkC39cRY2Tk3pv16XZvc96DVOFf8cVMN7ZJ03INU+dpW
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: redis
        app.kubernetes.io/name: redis
      name: redis
      namespace: redis
    type: Opaque

