apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: redis-master
  namespace: redis
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:  StatefulSet
    name: redis-master
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: redis-replicas
  namespace: redis
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:  StatefulSet
    name: redis-replicas
  updatePolicy:
    updateMode: "Off"
---
