apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/k8s-social/gitops.git
    path: manifests/redis
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-sentinel
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/k8s-social/gitops.git
    path: manifests/redis-sentinel
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-sentinel
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
---
