
kind: Service
apiVersion: v1
metadata:
  name: nginx-ingress-service
  namespace: kube-system
spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
  type: LoadBalancer
---
