apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: default
spec:
  encryptedData:
    api-key: AgCuKvHKBt6pswx0emAgEeEhc2ZXJEDYxtkN8E8dcBKQKW70SauoCAjWrtgFpCwXWqTGcwQb21REZlHL4AaVlanLmpGewEgG0YrvPKzrZYh8zQC4q0l/4jaJw8RwFrfXtqaP9x/8k5rVna2rs2LWOvOWrSzhoKKZfhLEp5NPr1VDuMhIPDs4+8CxKIhC36Amm6/nhzjlcajNY6d4mP6EL3lT1fR32EatcEudKJMW9qZbPLV5eWbRdwMg2jlAT4dxINbibu1WpFeq6MaStFYSUxBkETopKJYfehmRNYZgM9G7/uTmmQrSDzLHGyeB9C9Lar5E1mWo3T6+/wIZX+EwwBsSymWpWlATvuzUCPHIZ/QepJ08261ZKbk765BZIspxOxl+FsfE7xYdJk9/6uaCw+CJYNM9Av7L0qAV4T3J3CMEL6YaNZ3/7mmKr9Nn4yp5MFoJi53hdnzCaVWY97N8OI8LPvThhg0vbYFqrT0JCfeXBaimx1zwWoin+JnZIkdnZkQ/pOTmMa3+HStLeNcIqLqmig4xCKV5DPh+BuA9ahO85HHtu/xeSgKzumMtsp8vtslu2qlMg5tDKMTbvwNYvW2Vs9f3shdosm4jLl3baB5bfyqqcS2JFx6ax3PqO/V14sI+fwP8XQVXJpmDyPsbp/RgqeYwRnHXVKNpfTU10DmCHQZjR/FVH1BTWt8kpmn+yj5uE99aoM5HY27pIfvUujj3IZgn6qQA1hxZEQXb25F+n2t0CudO1KHyIpjDhrXxZYdl0Q==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: default

