apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: kube-system
spec:
  encryptedData:
    api-key: AgCQ4zbINqeXgPZStvQWT80OQZoPYw08859Hi2IH6HDHaRVhBMJoSpGdDKncdnli5m6582aIXTbqchC8rmvCe3Xvjfdz4GHnFOZ+eIUt6H5yt5mzEJbeirObWuXA93cquaYar0Kn4NDKUZ4HhHEF5iBXUSlccNvlXnx6ZbYCzbV4EX0ealg0CR8UXFay7CV+ZoZj+iEfuWZNqkniLeyOXjoSP3glgkG4Q27WdySNhrphQCSrTo/0oysZiFcbwAiSYyNhf+QTjz+qTQRkHniQ2m4Zh4eloS0ximO2Ub7oUVzmu0u9pYC9mVcHng7r5IpqgpVRWc2Y8fdicUceYaIEmEkEou+EeTPn1oL7JWYu4UczPqoWckyW5zAb5n/ihNR+z0UGCeJz5e7JDvg5ki1ETtEVlGUCubRwUQ0tCBRz5xM/vguGkoufj4MV7R8ocXUYvH8ZilSXHjJ1BBJia3okjHpHZdZE2PLEEm32yJ88wI4xV4Ok5Gg+R5LPnyb7bqi/8Eq2+2/R4G+QjKPkx4aWUgtUXCRqY3qbWITHYLMmhacpunr8Ntgir3Qwww+pedBKa3MVwc1M4etnfHXapavO/04psDPOm0S0huFdVIxEgUxciakBzyvptPQx0I2pCk4+lwt4UAjLQkuD5FUXWh1t46CgFKaledoAfePlRC4UZKjoLUrnC59ATdPxqZH/e/2xoAq4IJY1ZeWLKKcCuv/ohAxd6BbvFvZM5hm+BnVR4+KoSPP+vQlmSvIig2H9HCqtjnorjA==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: kube-system

